#!/usr/bin/env bash
set -e

if python3 --version &>/dev/null; then
  # Use python3, if the `python3` command exists
  python3 $@
else
  # Otherwise we use `python` hoping that `python`
  # is an alias of `python3`, because this is NOT a python2 script.
  # This strange invocation is due to a weird behavior of windows
  # that for some reason maps python to python3, and when python3 is invoked
  # it opens the store
  python $@
fi
